import { Inter } from "next/font/google";
import Link from "next/link";
// import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header>
        <nav>
          <menu>
                <li>
                    <Link href="/">Home</Link>
                </li>
                <li>
                    <Link href="/films">All Films</Link>
                </li>
                <li>
                    <Link href="/films/insert">Add Film</Link>
                </li>
          </menu></nav>
      </header>
        
        {children}
        
        </body>
    </html>
  );
}
